const fs = require('fs')
const file = fs.readFileSync('./index.html', { encoding: 'utf8' })
const d = (new Date()).toISOString()
const result = file.replace(/<date datetime=".*<\/date>/g, `<date datetime="${d}">${d}</date>`)
fs.writeFileSync('./index.html', result)
