name: test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update Timestamp
        run: |
          sed -i'' -e "s/<date>.*\<\/date>/<date>$(date +"%F at %H:%M %Z")<\/date>/g" index.html
          cat index.html
          git status
